spring:
  application:
    name: Chinese-Spring-eureka #指定服务名
  zipkin: #链式追踪
    base-url: http://39.105.49.14:9411
  boot: #服务监控
    admin:
      client:
        url: http://39.105.49.14:8886
server:
  port: 8921 #服务端口

eureka:
  instance:
    hostname: host #服务器地址，本地添localhost
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，本身就是所有无需注册
    fetchRegistry: true #是否从Eureka中获取注册信息
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://121.40.88.192:8921/eureka/,http://123.57.255.87:8921/eureka/,http://207.148.111.193:8921/eureka/

#服务监控配置
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info #如果改成 include: * 监控所有